### PR TITLE
Added WebDriverWait to findElement by tagname

### PR DESCRIPTION
**Pull request by SherifWaly**
PR for #92

### CODE REVIEW

**Comment by SherifWaly** [comment]
@amihaiemil The tests passes when I use ``ChromeDriver`` locally but with phantomJs the tests fail. I've tried to add ``WebDriverWait`` as the error happens when calling ``driver.findElement(By.tagName("body"))`` at LiveWebPage as I see that the driver times out before finding the element.
Is phantomJs too slow to reach links for example at the second page?

**Comment by amihaiemil** [comment]
@SherifWaly Yes, it might be the case...

**Comment by SherifWaly** [comment]
@amihaiemil So should I change it to ChromeDriver (what would be the driver path in this case?)

**Comment by amihaiemil** [comment]
@SherifWaly No, that's not an option. It won't run on the server since there is no graphics there, it has to be a headless browser. Let's leave it like this for now. We have a bigger issue, anyway: https://github.com/opencharles/charles/issues/96 ... probably will do the switch in the near future, when I have more time :)

**Pull request closed without merging**
