### PR TITLE
sudo

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #67

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@original-brownbear I'm having the [same](https://github.com/yegor256/rultor/issues/1108) problem here - apparently rultor cannot write to my repo, so I invited it to be a collaborator. Can you accept it? :D

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by original-brownbear** [comment]
@amihaiemil all happy now right ? :)

**Comment by amihaiemil** [comment]
@original-brownbear yup, thanks a lot :D

**Pull request merged**
